enum OperatingSystem {
  WINDOWS
  MACOS
  LINUX
}

enum KeyboardLayout {
  DE_CH
  DE_DE
  EN_US
  SR_LATIN_CS
}

enum DisplaySize {
  SIZE_12
  SIZE_13
  SIZE_14
  SIZE_15
  SIZE_16
  SIZE_17
  SIZE_18
}

enum ModelYear {
  YEAR_2015
  YEAR_2016
  YEAR_2017
  YEAR_2018
  YEAR_2019
  YEAR_2020
  YEAR_2021
}

type Device {
  operatingSystem: OperatingSystem!
  displaySize: DisplaySize!
  keyboardLayout: KeyboardLayout!
  modelYear: ModelYear!
  comment: String
  lendPeriods: [LendPeriod] @relation
}

type LendPeriod {
  startTs: Float!
  endTs: Float!
  device: Device
}

type Query {
  devices: [Device!]
  lendPeriodsByDevice(deviceId: ID!): [LendPeriod!]
    @resolver(name: "GetDeviceLendPeriods")
}
